# GenApiList.cmake - extract the function-pointer member names from MinaModAPI.h.
#
# This is the whole of the "code generator": an X-macro list of names, from which
# C++ deduces every type itself. Names only, so no regex has to understand C
# declarator syntax.
#
# Also sets MML_API_COUNT in the caller's scope.

function(mml_generate_api_list HEADER OUT_FILE)
    if(NOT EXISTS "${HEADER}")
        message(FATAL_ERROR "mml_generate_api_list: no such header: ${HEADER}")
    endif()

    # Members look like:  void*  ( *InstallHook )( const char* hookName, ... );
    file(STRINGS "${HEADER}" _lines REGEX "\\([ \t]*\\*[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*\\)")

    set(_out "// Generated by cmake/GenApiList.cmake from MinaModAPI.h. Do not edit.\n")
    set(_count 0)
    foreach(_line IN LISTS _lines)
        # Skip the callback typedefs, which share the (*Name) shape but are not
        # members: typedef void( *MM_HookCallback )( void* pCtx );
        if(_line MATCHES "^[ \t]*typedef")
            continue()
        endif()

        string(REGEX REPLACE "^.*\\([ \t]*\\*[ \t]*([A-Za-z_][A-Za-z0-9_]*)[ \t]*\\).*$"
               "\\1" _name "${_line}")
        string(APPEND _out "MM_FN(${_name})\n")
        math(EXPR _count "${_count} + 1")
    endforeach()

    if(_count EQUAL 0)
        message(FATAL_ERROR
            "mml_generate_api_list: extracted 0 members from ${HEADER}. "
            "The struct's shape changed - fix the regex rather than shipping an empty binding.")
    endif()

    # Write-if-different rather than file(GENERATE): works in script mode too, and
    # an unchanged header does not touch the timestamp and trigger a rebuild.
    get_filename_component(_dir "${OUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${_dir}")
    file(WRITE "${OUT_FILE}.tmp" "${_out}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT_FILE}.tmp" "${OUT_FILE}")
    file(REMOVE "${OUT_FILE}.tmp")

    message(STATUS "minamodlua: extracted ${_count} API members from MinaModAPI.h")
    set(MML_API_COUNT "${_count}" PARENT_SCOPE)
endfunction()

# Trailing `// ...` comments on the struct members. Upstream's own words, so
# they cannot go stale against the pin; only 56 of 372 members have one.
function(mml_generate_api_comments HEADER OUT_FILE)
    if(NOT EXISTS "${HEADER}")
        message(FATAL_ERROR "mml_generate_api_comments: no such header: ${HEADER}")
    endif()

    file(STRINGS "${HEADER}" _lines REGEX "\\([ \t]*\\*[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*\\).*//")

    set(_out "// Generated by cmake/GenApiList.cmake from MinaModAPI.h. Do not edit.\n")
    set(_count 0)
    foreach(_line IN LISTS _lines)
        if(_line MATCHES "^[ \t]*typedef")
            continue()
        endif()
        string(REGEX REPLACE "^.*\\([ \t]*\\*[ \t]*([A-Za-z_][A-Za-z0-9_]*)[ \t]*\\).*$" "\\1" _name "${_line}")
        string(REGEX REPLACE "^.*//[ \t]*(.*)$" "\\1" _text "${_line}")
        string(REPLACE "\\" "\\\\" _text "${_text}")
        string(REPLACE "\"" "\\\"" _text "${_text}")
        string(STRIP "${_text}" _text)
        if(_text)
            string(APPEND _out "MM_DOC(${_name}, \"${_text}\")\n")
            math(EXPR _count "${_count} + 1")
        endif()
    endforeach()

    if(_count EQUAL 0)
        message(FATAL_ERROR
            "mml_generate_api_comments: extracted 0 comments from ${HEADER}. "
            "The struct's shape changed - fix the regex rather than shipping an undocumented API.")
    endif()

    get_filename_component(_dir "${OUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${_dir}")
    file(WRITE "${OUT_FILE}.tmp" "${_out}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT_FILE}.tmp" "${OUT_FILE}")
    file(REMOVE "${OUT_FILE}.tmp")
    message(STATUS "minamodlua: extracted ${_count} API comments from MinaModAPI.h")
endfunction()

# Tokens that can only ever be part of a type, never a parameter name.
#
# These are matched as whole list items rather than stripped with a regex,
# because CMake's regex engine has no word-boundary escape: in "\\bconst\\b" the
# `\b` is a literal 'b', so that pattern matches "bconstb" and leaves "const"
# alone. Splitting into tokens and comparing them is the only reliable way.
set(_MML_CV_QUALIFIERS const volatile restrict __restrict __restrict__)
set(_MML_TAG_KEYWORDS struct enum union)
set(_MML_TYPE_KEYWORDS
    void bool _Bool char wchar_t char8_t char16_t char32_t
    short int long float double signed unsigned
    size_t ssize_t ptrdiff_t intptr_t uintptr_t intmax_t uintmax_t
    int8_t int16_t int32_t int64_t uint8_t uint16_t uint32_t uint64_t)

# One parameter declaration -> the name it declares, or "" when there is not one
# we can be certain of. Empty is safe: it degrades to a bare type in the docs.
# A guess is not safe, because a wrong name that keeps the parameter *count*
# sails straight past describe_sig::usable() and mislabels the argument.
function(_mml_param_name OUT_VAR DECL)
    set(_d "${DECL}")
    string(REGEX REPLACE "\\[[^]]*\\]" " " _d "${_d}")  # `coords[4]` -> `coords`
    string(REGEX REPLACE "[*&]" " " _d "${_d}")         # detach pointer/reference punctuation
    string(STRIP "${_d}" _d)
    if(_d STREQUAL "")
        set("${OUT_VAR}" "" PARENT_SCOPE)
        return()
    endif()

    string(REGEX REPLACE "[ \t]+" ";" _tokens "${_d}")
    # cv-qualifiers never bear on which token is the name, and dropping them is
    # what lets `const char *const name` resolve to `name`.
    list(REMOVE_ITEM _tokens ${_MML_CV_QUALIFIERS})

    list(LENGTH _tokens _n)
    # A lone token is a bare type: `void (*PlayerSetJoules)(int32_t)`.
    if(_n LESS 2)
        set("${OUT_VAR}" "" PARENT_SCOPE)
        return()
    endif()

    math(EXPR _i "${_n} - 1")
    math(EXPR _j "${_n} - 2")
    list(GET _tokens ${_i} _cand)
    list(GET _tokens ${_j} _prev)

    if(NOT "${_cand}" MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        set(_cand "")            # `...`, or punctuation left over from an odd declarator
    elseif("${_cand}" IN_LIST _MML_TYPE_KEYWORDS OR "${_cand}" IN_LIST _MML_TAG_KEYWORDS)
        set(_cand "")            # unnamed: `unsigned int`, `const char*`, `long long`
    elseif("${_cand}" STREQUAL "${_prev}")
        set(_cand "")            # a repeated token is a type spelling, not a name
    elseif("${_prev}" IN_LIST _MML_TAG_KEYWORDS)
        set(_cand "")            # unnamed: `struct MM_Thing` is entirely the type
    endif()

    set("${OUT_VAR}" "${_cand}" PARENT_SCOPE)
endfunction()

# Parameter names, which C++ deduction erases. Paired positionally with the
# compiler-deduced types and used only when the counts agree, so a bad parse
# drops the names rather than mislabelling an argument.
#
# That guard only compares counts, though, so it is blind to a misparse that
# yields the right *number* of wrong names. Everything below therefore keeps the
# entry count equal to the real parameter count and emits "" whenever the name
# is not certain.
function(mml_generate_api_args HEADER OUT_FILE)
    if(NOT EXISTS "${HEADER}")
        message(FATAL_ERROR "mml_generate_api_args: no such header: ${HEADER}")
    endif()

    file(STRINGS "${HEADER}" _lines REGEX "\\([ \t]*\\*[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*\\)[ \t]*\\(")

    set(_out "// Generated by cmake/GenApiList.cmake from MinaModAPI.h. Do not edit.\n")
    set(_count 0)
    foreach(_line IN LISTS _lines)
        if(_line MATCHES "^[ \t]*typedef")
            continue()
        endif()

        # Comments come off before anything splits on commas: `int a /* first */,
        # int b` otherwise parses to "/|b", which keeps the count and so is
        # exactly the kind of failure the downstream guard cannot see.
        string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" " " _line "${_line}")
        string(REGEX REPLACE "//.*$" "" _line "${_line}")

        string(REGEX REPLACE "^.*\\([ \t]*\\*[ \t]*([A-Za-z_][A-Za-z0-9_]*)[ \t]*\\).*$" "\\1" _name "${_line}")
        string(REGEX REPLACE "^[^(]*\\([ \t]*\\*[^)]*\\)[ \t]*\\(([^)]*)\\).*$" "\\1" _params "${_line}")
        string(STRIP "${_params}" _params)

        # Joined by hand rather than via list(APPEND): appending "" to an empty
        # list is a no-op, so `(int, int)` would collapse to "" instead of "|"
        # and break the one invariant describe_sig::usable() relies on.
        set(_joined "")
        set(_n 0)
        if(NOT _params STREQUAL "")
            string(REPLACE "," ";" _plist "${_params}")
            foreach(_p IN LISTS _plist)
                _mml_param_name(_pname "${_p}")
                if(_n GREATER 0)
                    string(APPEND _joined "|")
                endif()
                string(APPEND _joined "${_pname}")
                math(EXPR _n "${_n} + 1")
            endforeach()
        endif()

        string(APPEND _out "MM_ARGS(${_name}, \"${_joined}\")\n")
        math(EXPR _count "${_count} + 1")
    endforeach()

    if(_count EQUAL 0)
        message(FATAL_ERROR
            "mml_generate_api_args: extracted 0 members from ${HEADER}. "
            "The struct's shape changed - fix the regex rather than shipping unlabelled parameters.")
    endif()

    get_filename_component(_dir "${OUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${_dir}")
    file(WRITE "${OUT_FILE}.tmp" "${_out}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT_FILE}.tmp" "${OUT_FILE}")
    file(REMOVE "${OUT_FILE}.tmp")

    message(STATUS "minamodlua: extracted ${_count} API parameter lists from MinaModAPI.h")
endfunction()
