# GenApiList.cmake - extract the function-pointer member names from MinaModAPI.h.
#
# This is the whole of the "code generator": an X-macro list of names, from which
# C++ deduces every type itself. Names only, so no regex has to understand C
# declarator syntax.
#
# Also sets MML_API_COUNT in the caller's scope.

function(mml_generate_api_list HEADER OUT_FILE)
    if(NOT EXISTS "${HEADER}")
        message(FATAL_ERROR "mml_generate_api_list: no such header: ${HEADER}")
    endif()

    # Members look like:  void*  ( *InstallHook )( const char* hookName, ... );
    file(STRINGS "${HEADER}" _lines REGEX "\\([ \t]*\\*[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*\\)")

    set(_out "// Generated by cmake/GenApiList.cmake from MinaModAPI.h. Do not edit.\n")
    set(_count 0)
    foreach(_line IN LISTS _lines)
        # Skip the callback typedefs, which share the (*Name) shape but are not
        # members: typedef void( *MM_HookCallback )( void* pCtx );
        if(_line MATCHES "^[ \t]*typedef")
            continue()
        endif()

        string(REGEX REPLACE "^.*\\([ \t]*\\*[ \t]*([A-Za-z_][A-Za-z0-9_]*)[ \t]*\\).*$"
               "\\1" _name "${_line}")
        string(APPEND _out "MM_FN(${_name})\n")
        math(EXPR _count "${_count} + 1")
    endforeach()

    if(_count EQUAL 0)
        message(FATAL_ERROR
            "mml_generate_api_list: extracted 0 members from ${HEADER}. "
            "The struct's shape changed - fix the regex rather than shipping an empty binding.")
    endif()

    # Write-if-different rather than file(GENERATE): works in script mode too, and
    # an unchanged header does not touch the timestamp and trigger a rebuild.
    get_filename_component(_dir "${OUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${_dir}")
    file(WRITE "${OUT_FILE}.tmp" "${_out}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${OUT_FILE}.tmp" "${OUT_FILE}")
    file(REMOVE "${OUT_FILE}.tmp")

    message(STATUS "minamodlua: extracted ${_count} API members from MinaModAPI.h")
    set(MML_API_COUNT "${_count}" PARENT_SCOPE)
endfunction()
